--------------------------------------------------------
--  Fichier créé - vendredi-juin-05-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence LIVRAISON_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EYA"."LIVRAISON_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BATEAU
--------------------------------------------------------

   CREATE SEQUENCE  "EYA"."SEQ_BATEAU"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BATEAUX
--------------------------------------------------------

   CREATE SEQUENCE  "EYA"."SEQ_BATEAUX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EMPLOYE
--------------------------------------------------------

   CREATE SEQUENCE  "EYA"."SEQ_EMPLOYE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EMPLOYEES
--------------------------------------------------------

   CREATE SEQUENCE  "EYA"."SEQ_EMPLOYEES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 23 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FRIGO
--------------------------------------------------------

   CREATE SEQUENCE  "EYA"."SEQ_FRIGO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FRIGOS
--------------------------------------------------------

   CREATE SEQUENCE  "EYA"."SEQ_FRIGOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LIVRAISON
--------------------------------------------------------

   CREATE SEQUENCE  "EYA"."SEQ_LIVRAISON"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LIVRAISONS
--------------------------------------------------------

   CREATE SEQUENCE  "EYA"."SEQ_LIVRAISONS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PECHE
--------------------------------------------------------

   CREATE SEQUENCE  "EYA"."SEQ_PECHE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PECHES
--------------------------------------------------------

   CREATE SEQUENCE  "EYA"."SEQ_PECHES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QUAI
--------------------------------------------------------

   CREATE SEQUENCE  "EYA"."SEQ_QUAI"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QUAIS
--------------------------------------------------------

   CREATE SEQUENCE  "EYA"."SEQ_QUAIS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BATEAU
--------------------------------------------------------

  CREATE TABLE "EYA"."BATEAU" 
   (	"IDBATEAU" NUMBER, 
	"NOMBATEAU" VARCHAR2(100 BYTE), 
	"IMMATRICULATION" VARCHAR2(50 BYTE), 
	"CAPACITE" NUMBER, 
	"LONGEUR" NUMBER(5,2), 
	"AGE_BATEAU" NUMBER, 
	"DATE_DERNIERE_MAINTENANCE" DATE, 
	"DISPONIBLE" NUMBER(1,0), 
	"ID_EMPLOYE" NUMBER, 
	"IDQUAI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BATEAUX
--------------------------------------------------------

  CREATE TABLE "EYA"."BATEAUX" 
   (	"IDBATEAU" NUMBER, 
	"NOMBATEAU" VARCHAR2(100 BYTE), 
	"IMMATRICULATION" VARCHAR2(50 BYTE), 
	"CAPACITE" NUMBER, 
	"LONGEUR" NUMBER(5,2), 
	"AGE_BATEAU" NUMBER, 
	"DATE_DERNIERE_MAINTENANCE" DATE, 
	"ETAT" VARCHAR2(50 BYTE), 
	"ID_EMPLOYE" NUMBER, 
	"IDQUAI" NUMBER, 
	"FREQUENCE_SORTIES" NUMBER DEFAULT 0, 
	"DATE_PROCHAINE_MAINTENANCE" DATE, 
	"CODE_SECRET" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "EYA"."EMPLOYEES" 
   (	"ID_EMPLOYE" NUMBER, 
	"CIN" VARCHAR2(20 BYTE), 
	"SALAIRE" NUMBER(10,2), 
	"DATE_RECRUTEMENT" DATE, 
	"STATUT" VARCHAR2(50 BYTE), 
	"POSITION" VARCHAR2(100 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"NOM" VARCHAR2(50 BYTE), 
	"TELEPHONE" VARCHAR2(8 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"RFID_UID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FRIGOS
--------------------------------------------------------

  CREATE TABLE "EYA"."FRIGOS" 
   (	"IDFRIGO" NUMBER, 
	"REFERENCE" VARCHAR2(100 BYTE), 
	"CAPACITE" NUMBER, 
	"TEMPERATURE" NUMBER(5,2), 
	"STATUT" VARCHAR2(50 BYTE), 
	"TYPE_POISSON" VARCHAR2(100 BYTE), 
	"OCCUPATION" NUMBER, 
	"DATE_RESERVATION" DATE DEFAULT SYSDATE, 
	"ID_EMPLOYE" NUMBER, 
	"TELEPHONE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIVRAISONS
--------------------------------------------------------

  CREATE TABLE "EYA"."LIVRAISONS" 
   (	"IDLIVRAISON" NUMBER, 
	"DATELIVRAISON" DATE, 
	"ADRESSELIVRAISON" VARCHAR2(200 BYTE), 
	"STATUT" VARCHAR2(50 BYTE), 
	"TYPETRANSPORT" VARCHAR2(100 BYTE), 
	"PRIXLIVRAISON" VARCHAR2(50 BYTE), 
	"ID_EMPLOYE" NUMBER, 
	"VEHICULE" VARCHAR2(100 BYTE), 
	"DUREE" NUMBER, 
	"DATE_DEPART" TIMESTAMP (6), 
	"DUREE_ESTIMEE" NUMBER, 
	"REFERENCE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PECHES
--------------------------------------------------------

  CREATE TABLE "EYA"."PECHES" 
   (	"IDLOT" NUMBER, 
	"REFERENCE" VARCHAR2(100 BYTE), 
	"ESPECE" VARCHAR2(100 BYTE), 
	"QUANTITE" NUMBER, 
	"DATECAPTURE" DATE, 
	"IDBATEAU" NUMBER, 
	"IDFRIGO" NUMBER, 
	"ID_PECHEUR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRESENCE
--------------------------------------------------------

  CREATE TABLE "EYA"."PRESENCE" 
   (	"ID" NUMBER, 
	"ID_EMPLOYE" NUMBER, 
	"DATE_PRESENCE" DATE, 
	"HEURE_ARRIVEE" TIMESTAMP (6), 
	"HEURE_DEPART" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table QUAIS
--------------------------------------------------------

  CREATE TABLE "EYA"."QUAIS" 
   (	"IDQUAI" NUMBER, 
	"NUMERO" NUMBER, 
	"LOCATION" VARCHAR2(100 BYTE), 
	"CAPACITE" NUMBER, 
	"ETAT" VARCHAR2(30 BYTE), 
	"TARIF_LOCATION" NUMBER(10,2), 
	"DUREE_LOCATION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEST_TABLE
--------------------------------------------------------

  CREATE TABLE "EYA"."TEST_TABLE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into EYA.BATEAU
SET DEFINE OFF;
REM INSERTING into EYA.BATEAUX
SET DEFINE OFF;
Insert into EYA.BATEAUX (IDBATEAU,NOMBATEAU,IMMATRICULATION,CAPACITE,LONGEUR,AGE_BATEAU,DATE_DERNIERE_MAINTENANCE,ETAT,ID_EMPLOYE,IDQUAI,FREQUENCE_SORTIES,DATE_PROCHAINE_MAINTENANCE,CODE_SECRET) values (6,'tasnim','TN-1236-123123',23,60,6,to_date('25-04-26','DD-MM-RR'),'En mer',1,null,0,null,3333);
Insert into EYA.BATEAUX (IDBATEAU,NOMBATEAU,IMMATRICULATION,CAPACITE,LONGEUR,AGE_BATEAU,DATE_DERNIERE_MAINTENANCE,ETAT,ID_EMPLOYE,IDQUAI,FREQUENCE_SORTIES,DATE_PROCHAINE_MAINTENANCE,CODE_SECRET) values (2,'koukou','TN-5623-789456',26,25,60,to_date('29-03-25','DD-MM-RR'),'En mer',10,null,13,to_date('09-05-26','DD-MM-RR'),2222);
Insert into EYA.BATEAUX (IDBATEAU,NOMBATEAU,IMMATRICULATION,CAPACITE,LONGEUR,AGE_BATEAU,DATE_DERNIERE_MAINTENANCE,ETAT,ID_EMPLOYE,IDQUAI,FREQUENCE_SORTIES,DATE_PROCHAINE_MAINTENANCE,CODE_SECRET) values (11,'tn','TN-8458-84',4,5,5,to_date('06-05-26','DD-MM-RR'),'En mer',10,null,3,to_date('12-11-26','DD-MM-RR'),7451);
Insert into EYA.BATEAUX (IDBATEAU,NOMBATEAU,IMMATRICULATION,CAPACITE,LONGEUR,AGE_BATEAU,DATE_DERNIERE_MAINTENANCE,ETAT,ID_EMPLOYE,IDQUAI,FREQUENCE_SORTIES,DATE_PROCHAINE_MAINTENANCE,CODE_SECRET) values (1,'barbarous','TN-1233-2',50,12,5,to_date('12-05-26','DD-MM-RR'),'En mer',14,null,4,to_date('12-11-26','DD-MM-RR'),1111);
REM INSERTING into EYA.EMPLOYEES
SET DEFINE OFF;
Insert into EYA.EMPLOYEES (ID_EMPLOYE,CIN,SALAIRE,DATE_RECRUTEMENT,STATUT,POSITION,PRENOM,NOM,TELEPHONE,EMAIL,RFID_UID) values (10,'44414111',2000,to_date('06-04-18','DD-MM-RR'),'Actif','Marin','h','h',null,null,null);
Insert into EYA.EMPLOYEES (ID_EMPLOYE,CIN,SALAIRE,DATE_RECRUTEMENT,STATUT,POSITION,PRENOM,NOM,TELEPHONE,EMAIL,RFID_UID) values (11,'11111111',2000,to_date('02-04-26','DD-MM-RR'),'Inactif','Pêcheur','manana','ben aissa','23614589','mannena@gmail.com',null);
Insert into EYA.EMPLOYEES (ID_EMPLOYE,CIN,SALAIRE,DATE_RECRUTEMENT,STATUT,POSITION,PRENOM,NOM,TELEPHONE,EMAIL,RFID_UID) values (15,'66666666',5000,to_date('17-04-26','DD-MM-RR'),'Actif','Livreur','aziz','azri','85478456','aziz@gmail.com',null);
Insert into EYA.EMPLOYEES (ID_EMPLOYE,CIN,SALAIRE,DATE_RECRUTEMENT,STATUT,POSITION,PRENOM,NOM,TELEPHONE,EMAIL,RFID_UID) values (12,'22222222',2000,to_date('15-04-26','DD-MM-RR'),'Inactif','Sécurité','farah','mejeldi','24617788','farha@gmail.com',null);
Insert into EYA.EMPLOYEES (ID_EMPLOYE,CIN,SALAIRE,DATE_RECRUTEMENT,STATUT,POSITION,PRENOM,NOM,TELEPHONE,EMAIL,RFID_UID) values (13,'33333333',5000,to_date('01-04-26','DD-MM-RR'),'Inactif','Livreur','eya','mhamdi','11221312','eya@gmail.com','64:51:91:05');
Insert into EYA.EMPLOYEES (ID_EMPLOYE,CIN,SALAIRE,DATE_RECRUTEMENT,STATUT,POSITION,PRENOM,NOM,TELEPHONE,EMAIL,RFID_UID) values (14,'21313122',1222,to_date('21-04-26','DD-MM-RR'),'Actif','Pêcheur','aaaa','aazzz','22222222','dhafersmaoui8@gmail.com',null);
Insert into EYA.EMPLOYEES (ID_EMPLOYE,CIN,SALAIRE,DATE_RECRUTEMENT,STATUT,POSITION,PRENOM,NOM,TELEPHONE,EMAIL,RFID_UID) values (16,'88888888',5000,to_date('15-04-26','DD-MM-RR'),'Inactif','Marin','yoser','mofti','22114563','yos@gmail.com',null);
Insert into EYA.EMPLOYEES (ID_EMPLOYE,CIN,SALAIRE,DATE_RECRUTEMENT,STATUT,POSITION,PRENOM,NOM,TELEPHONE,EMAIL,RFID_UID) values (17,'99999999',6000,to_date('24-04-26','DD-MM-RR'),'Actif','Technicien','mohamed ali','ben aissa','93566555','medali@gmail.com',null);
Insert into EYA.EMPLOYEES (ID_EMPLOYE,CIN,SALAIRE,DATE_RECRUTEMENT,STATUT,POSITION,PRENOM,NOM,TELEPHONE,EMAIL,RFID_UID) values (18,'55555555',8000,to_date('06-05-26','DD-MM-RR'),'Actif','RH','sisi','sasa','55555555','sisi@gmail.com',null);
Insert into EYA.EMPLOYEES (ID_EMPLOYE,CIN,SALAIRE,DATE_RECRUTEMENT,STATUT,POSITION,PRENOM,NOM,TELEPHONE,EMAIL,RFID_UID) values (19,'12345678',1200,to_date('26-03-26','DD-MM-RR'),'Actif','P?cheur','ahmed','khalil','22222222','eyazayeti587@gmail.com',null);
Insert into EYA.EMPLOYEES (ID_EMPLOYE,CIN,SALAIRE,DATE_RECRUTEMENT,STATUT,POSITION,PRENOM,NOM,TELEPHONE,EMAIL,RFID_UID) values (21,'78452212',2000,to_date('08-05-26','DD-MM-RR'),'Actif','Livreur','mannena','ben issa','29456178','mannena@gmail.com',null);
Insert into EYA.EMPLOYEES (ID_EMPLOYE,CIN,SALAIRE,DATE_RECRUTEMENT,STATUT,POSITION,PRENOM,NOM,TELEPHONE,EMAIL,RFID_UID) values (22,'12563544',5000,to_date('16-05-26','DD-MM-RR'),'Inactif','RH','aziz','azri','44586152','aziz@gmail.com',null);
REM INSERTING into EYA.FRIGOS
SET DEFINE OFF;
Insert into EYA.FRIGOS (IDFRIGO,REFERENCE,CAPACITE,TEMPERATURE,STATUT,TYPE_POISSON,OCCUPATION,DATE_RESERVATION,ID_EMPLOYE,TELEPHONE) values (26238,'FRG-001',3000,36,'Disponible','Sardine',399,to_date('08-05-26','DD-MM-RR'),null,'55555555');
Insert into EYA.FRIGOS (IDFRIGO,REFERENCE,CAPACITE,TEMPERATURE,STATUT,TYPE_POISSON,OCCUPATION,DATE_RESERVATION,ID_EMPLOYE,TELEPHONE) values (44958,'FRG-002',2,2,'Disponible','Sardine',0,to_date('08-05-26','DD-MM-RR'),null,'55555555');
Insert into EYA.FRIGOS (IDFRIGO,REFERENCE,CAPACITE,TEMPERATURE,STATUT,TYPE_POISSON,OCCUPATION,DATE_RESERVATION,ID_EMPLOYE,TELEPHONE) values (12122,'FRG-5',10000,-2,'Disponible','Crevette',650,to_date('12-05-26','DD-MM-RR'),null,'565555555');
Insert into EYA.FRIGOS (IDFRIGO,REFERENCE,CAPACITE,TEMPERATURE,STATUT,TYPE_POISSON,OCCUPATION,DATE_RESERVATION,ID_EMPLOYE,TELEPHONE) values (30132,'FRG-8',2600,0,'Disponible','Saumon',800,to_date('16-05-26','DD-MM-RR'),null,'55555555');
REM INSERTING into EYA.LIVRAISONS
SET DEFINE OFF;
Insert into EYA.LIVRAISONS (IDLIVRAISON,DATELIVRAISON,ADRESSELIVRAISON,STATUT,TYPETRANSPORT,PRIXLIVRAISON,ID_EMPLOYE,VEHICULE,DUREE,DATE_DEPART,DUREE_ESTIMEE,REFERENCE) values (2,to_date('06-05-26','DD-MM-RR'),'mourouj 3','En chemin','Camion non frigorifique','5.0E+002',15,'Bateau de Transport-05',45,to_timestamp('16-05-26 18:53:20.000000000','DD-MM-RR HH24:MI:SSXFF'),9390.1000000000004,'LIV-55');
REM INSERTING into EYA.PECHES
SET DEFINE OFF;
Insert into EYA.PECHES (IDLOT,REFERENCE,ESPECE,QUANTITE,DATECAPTURE,IDBATEAU,IDFRIGO,ID_PECHEUR) values (72545,'REF-2026-3','Sardine',399,to_date('16-05-26','DD-MM-RR'),6,26238,11);
Insert into EYA.PECHES (IDLOT,REFERENCE,ESPECE,QUANTITE,DATECAPTURE,IDBATEAU,IDFRIGO,ID_PECHEUR) values (74143,'REF-2026-02','Crevette',550,to_date('12-05-26','DD-MM-RR'),6,12122,11);
Insert into EYA.PECHES (IDLOT,REFERENCE,ESPECE,QUANTITE,DATECAPTURE,IDBATEAU,IDFRIGO,ID_PECHEUR) values (36072,'REF-2026-55','Crevette',100,to_date('16-05-26','DD-MM-RR'),6,12122,11);
Insert into EYA.PECHES (IDLOT,REFERENCE,ESPECE,QUANTITE,DATECAPTURE,IDBATEAU,IDFRIGO,ID_PECHEUR) values (52700,'REF-2026-76','Saumon',800,to_date('16-05-26','DD-MM-RR'),6,30132,11);
REM INSERTING into EYA.PRESENCE
SET DEFINE OFF;
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (1,13,to_date('27-04-26','DD-MM-RR'),to_timestamp('27-04-26 22:42:53.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('27-04-26 22:43:03.774000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (2,13,to_date('27-04-26','DD-MM-RR'),to_timestamp('27-04-26 23:16:57.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('27-04-26 23:17:02.139000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (3,13,to_date('28-04-26','DD-MM-RR'),to_timestamp('28-04-26 11:14:44.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('28-04-26 11:14:55.844000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (4,13,to_date('28-04-26','DD-MM-RR'),to_timestamp('28-04-26 11:15:46.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('28-04-26 11:16:30.764000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (5,13,to_date('28-04-26','DD-MM-RR'),to_timestamp('28-04-26 11:18:08.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('28-04-26 11:18:13.968000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (6,13,to_date('28-04-26','DD-MM-RR'),to_timestamp('28-04-26 11:18:18.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('28-04-26 11:34:20.795000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (7,13,to_date('28-04-26','DD-MM-RR'),to_timestamp('28-04-26 11:34:52.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('28-04-26 11:40:28.524000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (8,13,to_date('28-04-26','DD-MM-RR'),to_timestamp('28-04-26 11:41:00.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('28-04-26 12:03:56.495000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (9,13,to_date('28-04-26','DD-MM-RR'),to_timestamp('28-04-26 15:47:58.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('28-04-26 16:00:08.467000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (10,13,to_date('28-04-26','DD-MM-RR'),to_timestamp('28-04-26 16:00:14.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('28-04-26 16:02:00.494000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (11,13,to_date('06-05-26','DD-MM-RR'),to_timestamp('06-05-26 21:17:22.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('06-05-26 21:17:32.080000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (12,13,to_date('06-05-26','DD-MM-RR'),to_timestamp('06-05-26 21:22:54.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('06-05-26 21:23:22.687000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (13,13,to_date('07-05-26','DD-MM-RR'),to_timestamp('07-05-26 12:56:54.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('07-05-26 12:56:59.311000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (14,13,to_date('07-05-26','DD-MM-RR'),to_timestamp('07-05-26 12:58:31.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('07-05-26 12:58:36.445000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (15,13,to_date('08-05-26','DD-MM-RR'),to_timestamp('08-05-26 14:26:08.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('08-05-26 14:26:38.195000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (16,13,to_date('08-05-26','DD-MM-RR'),to_timestamp('08-05-26 14:26:42.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('08-05-26 14:54:57.140000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (17,13,to_date('08-05-26','DD-MM-RR'),to_timestamp('08-05-26 14:55:02.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('08-05-26 16:04:00.988000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (18,13,to_date('08-05-26','DD-MM-RR'),to_timestamp('08-05-26 16:04:05.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('08-05-26 17:23:38.502000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (19,13,to_date('08-05-26','DD-MM-RR'),to_timestamp('08-05-26 17:23:59.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('08-05-26 18:56:02.449000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (20,13,to_date('08-05-26','DD-MM-RR'),to_timestamp('08-05-26 18:56:08.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('08-05-26 18:56:14.753000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (21,13,to_date('08-05-26','DD-MM-RR'),to_timestamp('08-05-26 18:56:20.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('08-05-26 18:57:29.029000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (22,13,to_date('08-05-26','DD-MM-RR'),to_timestamp('08-05-26 18:57:34.000000000','DD-MM-RR HH24:MI:SSXFF'),to_timestamp('08-05-26 19:19:10.314000000','DD-MM-RR HH24:MI:SSXFF'));
Insert into EYA.PRESENCE (ID,ID_EMPLOYE,DATE_PRESENCE,HEURE_ARRIVEE,HEURE_DEPART) values (23,13,to_date('08-05-26','DD-MM-RR'),to_timestamp('08-05-26 19:19:16.000000000','DD-MM-RR HH24:MI:SSXFF'),null);
REM INSERTING into EYA.QUAIS
SET DEFINE OFF;
Insert into EYA.QUAIS (IDQUAI,NUMERO,LOCATION,CAPACITE,ETAT,TARIF_LOCATION,DUREE_LOCATION) values (2,897969,'test',44,'Disponible',44,40);
Insert into EYA.QUAIS (IDQUAI,NUMERO,LOCATION,CAPACITE,ETAT,TARIF_LOCATION,DUREE_LOCATION) values (3,1,'zpneA',60,'Disponible',50,30);
Insert into EYA.QUAIS (IDQUAI,NUMERO,LOCATION,CAPACITE,ETAT,TARIF_LOCATION,DUREE_LOCATION) values (4,623900,'ygf',40,'Maintenance',5,4);
REM INSERTING into EYA.TEST_TABLE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_QUAIS
--------------------------------------------------------

  CREATE UNIQUE INDEX "EYA"."PK_QUAIS" ON "EYA"."QUAIS" ("IDQUAI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PECHES
--------------------------------------------------------

  CREATE UNIQUE INDEX "EYA"."PK_PECHES" ON "EYA"."PECHES" ("IDLOT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_BATEAU
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EYA"."TRG_BATEAU" 
BEFORE INSERT ON Bateau
FOR EACH ROW
BEGIN
    SELECT seq_bateau.NEXTVAL
    INTO :NEW.IdBateau
    FROM dual;
END;

/
ALTER TRIGGER "EYA"."TRG_BATEAU" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BATEAUX
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EYA"."TRG_BATEAUX" 
BEFORE INSERT ON BATEAUX
FOR EACH ROW
BEGIN
    SELECT SEQ_BATEAUX.NEXTVAL
    INTO :NEW.IDBATEAU
    FROM DUAL;
END;


/
ALTER TRIGGER "EYA"."TRG_BATEAUX" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_EMPLOYEES
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EYA"."TRG_EMPLOYEES" 
BEFORE INSERT ON Employees
FOR EACH ROW
BEGIN
    SELECT seq_employees.NEXTVAL
    INTO :NEW.id_employe
    FROM dual;
END;


/
ALTER TRIGGER "EYA"."TRG_EMPLOYEES" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_FRIGOS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EYA"."TRG_FRIGOS" 
BEFORE INSERT ON EYA.FRIGOS
FOR EACH ROW
BEGIN
    IF :NEW.IDFRIGO IS NULL THEN
        SELECT EYA.SEQ_FRIGOS.NEXTVAL 
        INTO :NEW.IDFRIGO 
        FROM DUAL;
    END IF;
END;


/
ALTER TRIGGER "EYA"."TRG_FRIGOS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_LIVRAISONS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EYA"."TRG_LIVRAISONS" 
BEFORE INSERT ON Livraisons
FOR EACH ROW
BEGIN
    SELECT seq_livraisons.NEXTVAL
    INTO :NEW.idLivraison
    FROM dual;
END;


/
ALTER TRIGGER "EYA"."TRG_LIVRAISONS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PECHES
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EYA"."TRG_PECHES" 
BEFORE INSERT ON PECHES
FOR EACH ROW
BEGIN
    IF :NEW.IDLOT IS NULL THEN
        SELECT SEQ_PECHES.NEXTVAL
        INTO :NEW.IDLOT
        FROM DUAL;
    END IF;
END;

/
ALTER TRIGGER "EYA"."TRG_PECHES" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_QUAIS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EYA"."TRG_QUAIS" 
BEFORE INSERT ON Quais
FOR EACH ROW
BEGIN
    IF :NEW.idQuai IS NULL THEN
        SELECT seq_quais.NEXTVAL
        INTO :NEW.idQuai
        FROM dual;
    END IF;
END;


/
ALTER TRIGGER "EYA"."TRG_QUAIS" ENABLE;
--------------------------------------------------------
--  Constraints for Table TEST_TABLE
--------------------------------------------------------

  ALTER TABLE "EYA"."TEST_TABLE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "EYA"."EMPLOYEES" ADD UNIQUE ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EYA"."EMPLOYEES" ADD PRIMARY KEY ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIVRAISONS
--------------------------------------------------------

  ALTER TABLE "EYA"."LIVRAISONS" ADD PRIMARY KEY ("IDLIVRAISON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FRIGOS
--------------------------------------------------------

  ALTER TABLE "EYA"."FRIGOS" ADD PRIMARY KEY ("IDFRIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BATEAU
--------------------------------------------------------

  ALTER TABLE "EYA"."BATEAU" ADD UNIQUE ("IMMATRICULATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EYA"."BATEAU" ADD PRIMARY KEY ("IDBATEAU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EYA"."BATEAU" MODIFY ("NOMBATEAU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRESENCE
--------------------------------------------------------

  ALTER TABLE "EYA"."PRESENCE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BATEAUX
--------------------------------------------------------

  ALTER TABLE "EYA"."BATEAUX" ADD PRIMARY KEY ("IDBATEAU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PECHES
--------------------------------------------------------

  ALTER TABLE "EYA"."PECHES" ADD CONSTRAINT "PK_PECHES" PRIMARY KEY ("IDLOT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QUAIS
--------------------------------------------------------

  ALTER TABLE "EYA"."QUAIS" ADD CONSTRAINT "PK_QUAIS" PRIMARY KEY ("IDQUAI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EYA"."QUAIS" ADD CONSTRAINT "CHK_CAPACITE" CHECK (capacite > 0) ENABLE;
  ALTER TABLE "EYA"."QUAIS" MODIFY ("NUMERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BATEAU
--------------------------------------------------------

  ALTER TABLE "EYA"."BATEAU" ADD CONSTRAINT "FK_BATEAU_EMPLOYE" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "EYA"."EMPLOYEES" ("ID_EMPLOYE") ENABLE;
  ALTER TABLE "EYA"."BATEAU" ADD CONSTRAINT "FK_BATEAU_QUAI" FOREIGN KEY ("IDQUAI")
	  REFERENCES "EYA"."QUAIS" ("IDQUAI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FRIGOS
--------------------------------------------------------

  ALTER TABLE "EYA"."FRIGOS" ADD CONSTRAINT "FK_FRIGO_EMPLOYE" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "EYA"."EMPLOYEES" ("ID_EMPLOYE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIVRAISONS
--------------------------------------------------------

  ALTER TABLE "EYA"."LIVRAISONS" ADD CONSTRAINT "FK_LIVRAISON_EMPLOYE" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "EYA"."EMPLOYEES" ("ID_EMPLOYE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PECHES
--------------------------------------------------------

  ALTER TABLE "EYA"."PECHES" ADD CONSTRAINT "FK_PECHES_BATEAU" FOREIGN KEY ("IDBATEAU")
	  REFERENCES "EYA"."BATEAUX" ("IDBATEAU") ENABLE;
  ALTER TABLE "EYA"."PECHES" ADD CONSTRAINT "FK_PECHE_FRIGO" FOREIGN KEY ("IDFRIGO")
	  REFERENCES "EYA"."FRIGOS" ("IDFRIGO") ENABLE;
  ALTER TABLE "EYA"."PECHES" ADD CONSTRAINT "FK_PECHE_PECHEUR" FOREIGN KEY ("ID_PECHEUR")
	  REFERENCES "EYA"."EMPLOYEES" ("ID_EMPLOYE") ENABLE;
