#include "mainwindow.h"
#include "Employeewindow.h"
#include "Frigowindow.h"
#include "temperaturealert.h"
#include <QSqlQuery>
#include <QSqlError>
#include <QRegularExpression>
#include <QSqlRecord>
#include "pechewindow.h"
#include "loginwindow.h"
#include <QApplication>
#include <QFont>
#include <QPixmap>
#include <QDebug>
#include <QMessageBox>
#include <QGraphicsOpacityEffect>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QStackedWidget>
#include <QPropertyAnimation>
#include "bateau.h"
#include <QStyle>
#include <QIcon>
#include <QStringList>
#include <QSystemTrayIcon>
#include <QTimer>
#include <QMovie>
#include <QPainter>

MainWindow::MainWindow(const QString& userName, const QString& userRole, QWidget *parent)
    : QMainWindow(parent), currentActiveBtn(nullptr), employeePage(nullptr), pechePage(nullptr), frigoPage(nullptr), bateauPage(nullptr), livraisonPage(nullptr), quaisPage(nullptr),
      loggedUserName(userName), loggedUserRole(userRole)
{
    setupUi();
    checkMaintenanceAlerts();

    // Initialize Arduino
    int ret = A.connect_arduino();
    switch(ret) {
        case(0): qDebug() << "Arduino connected to:" << A.getarduino_port_name(); break;
        case(1): qDebug() << "Arduino found but failed to connect."; break;
        case(-1): qDebug() << "Arduino not found."; break;
    }

    connect(A.getserial(), &QSerialPort::readyRead, this, &MainWindow::handleSerialData);

    // DEBUG: Force-read timer every second to ensure we don't miss data
    QTimer* forceReadTimer = new QTimer(this);
    connect(forceReadTimer, &QTimer::timeout, this, &MainWindow::handleSerialData);
    forceReadTimer->start(1000);

    // DEBUG: Pulse log to confirm app is alive
    QTimer* pulseTimer = new QTimer(this);
    connect(pulseTimer, &QTimer::timeout, this, [](){
        qDebug() << "--- MONITORING PULSE: App is alive and listening ---";
    });
    pulseTimer->start(2000);

    // Detect which employee table exists
    QSqlQuery testQuery;
    if (testQuery.exec("SELECT * FROM EMPLOYEES WHERE 1=0")) {
        activeEmployeeTable = "EMPLOYEES";
    } else {
        activeEmployeeTable = "EMPLOYEE";
    }
    qDebug() << "Using employee table:" << activeEmployeeTable;

    // Ensure database schema for presence system
    QSqlQuery setupQuery;
    setupQuery.exec(QString("ALTER TABLE %1 ADD RFID_UID VARCHAR2(50)").arg(activeEmployeeTable));
    
    // Create PRESENCE table if it doesn't exist
    setupQuery.exec("CREATE TABLE PRESENCE ("
                    "ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    "ID_EMPLOYE NUMBER, "
                    "DATE_PRESENCE DATE, "
                    "HEURE_ARRIVEE TIMESTAMP, "
                    "HEURE_DEPART TIMESTAMP)");

    // Initialize global properties
    qApp->setProperty("isDarkMode", isDarkMode);
    qApp->setProperty("isEnglish", isEnglish);
}

MainWindow::~MainWindow()
{
}

void MainWindow::setupUi()
{
    setWindowTitle("PortFlow - Dashboard");
    setMinimumSize(1400, 800);

    setStyleSheet(R"(
        QMainWindow {
            background-color: #F0F4F8;
        }
    )");

    QWidget* centralWidget = new QWidget(this);
    setCentralWidget(centralWidget);

    QHBoxLayout* mainLayout = new QHBoxLayout(centralWidget);
    mainLayout->setSpacing(0);
    mainLayout->setContentsMargins(0, 0, 0, 0);

    // Sidebar
    QFrame* sidebar = createSidebar();
    mainLayout->addWidget(sidebar);

    // Stacked Widget pour les pages
    stackedWidget = new QStackedWidget();
    stackedWidget->setStyleSheet("background-color: #F0F4F8;");

    // Page 0: Dashboard
    stackedWidget->addWidget(createDashboardPage());

    // Les autres pages seront créées à la demande
    mainLayout->addWidget(stackedWidget, 1);

    if (dashboardBtn) {
        setActiveButton(dashboardBtn);
    }
}

QFrame* MainWindow::createSidebar()
{
    QFrame* sidebar = new QFrame();
    sidebar->setFixedWidth(280);
    sidebar->setStyleSheet(R"(
        QFrame {
            background: qlineargradient(
                x1:0, y1:0, x2:0, y2:1,
                stop:0 #2B5EA6,
                stop:1 #5D9CEC
            );
        }
    )");

    QVBoxLayout* layout = new QVBoxLayout(sidebar);
    layout->setSpacing(0);
    layout->setContentsMargins(0, 0, 0, 0);

    // Logo section
    QFrame* logoFrame = new QFrame();
    logoFrame->setFixedHeight(180); // Increased from 160
    logoFrame->setStyleSheet("background: transparent;");
    QVBoxLayout* logoLayout = new QVBoxLayout(logoFrame);
    logoLayout->setAlignment(Qt::AlignCenter);
    logoLayout->setContentsMargins(0, 20, 20, 20); // Removed left margin to allow more left shift

    QFrame* logoContainer = new QFrame();
    logoContainer->setFixedSize(320, 180); // Increased from 240, 120
    logoContainer->setStyleSheet("background: transparent;");

    QLabel* logoLabel = new QLabel(logoContainer);
    logoLabel->setObjectName("sidebarLogoLabel");
    // Start small and invisible for the "thin air" effect
    logoLabel->setGeometry(80, 65, 150, 50); 
    
    QPixmap logoPix(":/images/images/logo.png");

    if (!logoPix.isNull()) {
        logoLabel->setPixmap(logoPix.scaled(320, 160, Qt::KeepAspectRatio, Qt::SmoothTransformation));
        logoLabel->setAlignment(Qt::AlignCenter);
        qDebug() << "Logo chargé depuis: :/images/images/logo.png";
    } else {
        logoLabel->setText("🚢");
        logoLabel->setStyleSheet(R"(
            QLabel {
                font-size: 60px;
                color: #2C3E50;
            }
        )");
        logoLabel->setAlignment(Qt::AlignCenter);
        qDebug() << "Attention: Logo non trouvé à :/images/images/logo.png - utilisation emoji";
    }

    logoLabel->setStyleSheet("background: transparent;");
    logoLayout->addWidget(logoContainer);
    layout->addWidget(logoFrame);

    // "Appears from Thin Air" Animation Sequence
    QTimer::singleShot(500, [logoLabel]() {
        // 1. Fade In
        QGraphicsOpacityEffect* opacity = new QGraphicsOpacityEffect(logoLabel);
        logoLabel->setGraphicsEffect(opacity);
        QPropertyAnimation* fadeAnim = new QPropertyAnimation(opacity, "opacity");
        fadeAnim->setDuration(1500);
        fadeAnim->setStartValue(0.0);
        fadeAnim->setEndValue(1.0);
        fadeAnim->setEasingCurve(QEasingCurve::InQuad);

        // 2. Scale & Wave (Grow from center)
        QPropertyAnimation* scaleAnim = new QPropertyAnimation(logoLabel, "geometry");
        QRect endRect = QRect(-20, 15, 300, 150); // Shifted even more to the left
        scaleAnim->setDuration(1800);
        scaleAnim->setStartValue(QRect(130, 90, 0, 0)); // Adjusted start center for x=-20
        scaleAnim->setEndValue(endRect);
        scaleAnim->setEasingCurve(QEasingCurve::OutElastic);

        fadeAnim->start(QPropertyAnimation::DeleteWhenStopped);
        scaleAnim->start(QPropertyAnimation::DeleteWhenStopped);

        // 3. Start persistent floating AFTER entrance
        QObject::connect(scaleAnim, &QPropertyAnimation::finished, [logoLabel, endRect]() {
            QPropertyAnimation* floatAnim = new QPropertyAnimation(logoLabel, "pos");
            QPoint startPos = endRect.topLeft();
            floatAnim->setDuration(3500);
            floatAnim->setStartValue(startPos);
            floatAnim->setKeyValueAt(0.5, startPos + QPoint(0, -10));
            floatAnim->setEndValue(startPos);
            floatAnim->setEasingCurve(QEasingCurve::InOutSine);
            floatAnim->setLoopCount(-1);
            floatAnim->start(QPropertyAnimation::DeleteWhenStopped);
        });
    });

    // Navigation
    QFrame* navFrame = new QFrame();
    navFrame->setStyleSheet("background: transparent;");
    QVBoxLayout* navLayout = new QVBoxLayout(navFrame);
    navLayout->setSpacing(8);
    navLayout->setContentsMargins(20, 20, 20, 20);

    dashboardBtn = createNavButton("🏠", "Dashboard", true);
    connect(dashboardBtn, &QPushButton::clicked, this, &MainWindow::onNavigateToDashboard);
    navLayout->addWidget(dashboardBtn);

    QString role = loggedUserRole.trimmed();
    qDebug() << "Current loggedUserRole:" << role;

    // Role-based access control:
    // Admin          → all modules visible
    // Pêcheur        → Pêche only
    // Marin          → Bateau only
    // Technicien     → Bateau only
    // Livreur        → Livraison only
    // RH             → Employés only
    // (empty role)   → all modules (developer/debug)

    bool isAdmin = role.compare("Admin", Qt::CaseInsensitive) == 0 || role.isEmpty();

    auto canAccess = [&](const QStringList& allowedRoles) -> bool {
        if (isAdmin) return true;
        for (const QString& r : allowedRoles) {
            if (role.compare(r, Qt::CaseInsensitive) == 0) return true;
        }
        return false;
    };

    // Bateaux: visible for Admin, Marin, Technicien
    bateauxBtn = createNavButton("⛵", "Bateaux");
    connect(bateauxBtn, &QPushButton::clicked, this, &MainWindow::onNavigateToBateaux);
    navLayout->addWidget(bateauxBtn);
    if (!canAccess({"Marin", "Technicien"})) bateauxBtn->hide();

    // Pêche: visible for Admin, Pêcheur
    pechesBtn = createNavButton("🐟", "Pêche");
    connect(pechesBtn, &QPushButton::clicked, this, &MainWindow::onNavigateToPeches);
    navLayout->addWidget(pechesBtn);
    if (!canAccess({"Pêcheur", "Pecheur"})) pechesBtn->hide();

    // Employés: visible for Admin, RH
    employeesBtn = createNavButton("👥", "Employés");
    connect(employeesBtn, &QPushButton::clicked, this, &MainWindow::onNavigateToEmployees);
    navLayout->addWidget(employeesBtn);
    if (!canAccess({"RH"})) employeesBtn->hide();

    // Frigos: visible for Admin only (no specific role assigned by user)
    QHBoxLayout* frigoRow = new QHBoxLayout();
    frigosBtn = createNavButton("🧊", "Frigos");
    frigoNotifyLabel1 = new QLabel("1️⃣🚨");
    frigoNotifyLabel2 = new QLabel("2️⃣🚨");
    QString notifyStyle = "font-size: 14px; background: transparent; color: #EF4444; font-weight: bold;";
    frigoNotifyLabel1->setStyleSheet(notifyStyle);
    frigoNotifyLabel2->setStyleSheet(notifyStyle);
    frigoNotifyLabel1->hide();
    frigoNotifyLabel2->hide();
    connect(frigosBtn, &QPushButton::clicked, this, &MainWindow::onNavigateToFrigos);
    frigoRow->addWidget(frigosBtn, 1);
    frigoRow->addWidget(frigoNotifyLabel1);
    frigoRow->addWidget(frigoNotifyLabel2);
    navLayout->addLayout(frigoRow);
    if (!isAdmin) {
        frigosBtn->hide();
        frigoNotifyLabel1->hide();
        frigoNotifyLabel2->hide();
    }

    // Livraison: visible for Admin, Livreur
    livraisonBtn = createNavButton("🚚", "Livraison");
    connect(livraisonBtn, &QPushButton::clicked, this, &MainWindow::onNavigateToLivraison);
    navLayout->addWidget(livraisonBtn);
    if (!canAccess({"Livreur"})) livraisonBtn->hide();

    // Quais: visible for Admin only
    quaisBtn = createNavButton("⚓", "Quais");
    connect(quaisBtn, &QPushButton::clicked, this, &MainWindow::onNavigateToQuais);
    navLayout->addWidget(quaisBtn);
    if (!isAdmin) quaisBtn->hide();

    QPushButton* settingsBtn = createNavButton("⚙️", "Paramètres");
    connect(settingsBtn, &QPushButton::clicked, this, &MainWindow::onSettingsClicked);
    navLayout->addWidget(settingsBtn);
    navLayout->addStretch();

    QPushButton* logoutBtn = createNavButton("🚪", "Quitter", false, true);
    connect(logoutBtn, &QPushButton::clicked, this, &MainWindow::onLogout);
    navLayout->addWidget(logoutBtn);

    layout->addWidget(navFrame, 1);

    return sidebar;
}

QPushButton* MainWindow::createNavButton(const QString& icon, const QString& text, bool isActive, bool isLogout)
{
    QPushButton* btn = new QPushButton(icon + "  " + text);
    QFont btnFont("Segoe UI", 12, QFont::Medium);
    btn->setFont(btnFont);
    btn->setCursor(Qt::PointingHandCursor);
    btn->setFixedHeight(55);
    btn->setProperty("navButton", true);

    if (isLogout) {
        btn->setStyleSheet(R"(
            QPushButton {
                background-color: rgba(255, 255, 255, 0.1);
                color: white;
                border: none;
                border-radius: 12px;
                text-align: left;
                padding-left: 20px;
            }
            QPushButton:hover {
                background-color: rgba(239, 68, 68, 0.8);
            }
        )");
    } else if (isActive) {
        btn->setStyleSheet(R"(
            QPushButton {
                background-color: rgba(255, 255, 255, 0.25);
                color: white;
                border: none;
                border-radius: 12px;
                text-align: left;
                padding-left: 20px;
                font-weight: bold;
            }
        )");
    } else {
        btn->setStyleSheet(R"(
            QPushButton {
                background-color: transparent;
                color: rgba(255, 255, 255, 0.9);
                border: none;
                border-radius: 12px;
                text-align: left;
                padding-left: 20px;
            }
            QPushButton:hover {
                background-color: rgba(255, 255, 255, 0.15);
            }
        )");
    }

    return btn;
}

void MainWindow::setActiveButton(QPushButton* activeBtn)
{
    if (currentActiveBtn && currentActiveBtn->property("navButton").toBool()) {
        currentActiveBtn->setStyleSheet(R"(
            QPushButton {
                background-color: transparent;
                color: rgba(255, 255, 255, 0.9);
                border: none;
                border-radius: 12px;
                text-align: left;
                padding-left: 20px;
            }
            QPushButton:hover {
                background-color: rgba(255, 255, 255, 0.15);
            }
        )");
    }

    currentActiveBtn = activeBtn;
    if (activeBtn) {
        activeBtn->setStyleSheet(R"(
            QPushButton {
                background-color: rgba(255, 255, 255, 0.25);
                color: white;
                border: none;
                border-radius: 12px;
                text-align: left;
                padding-left: 20px;
                font-weight: bold;
            }
        )");
    }
}

void MainWindow::switchPage(int index)
{

    QWidget* currentWidget = stackedWidget->currentWidget();
    QGraphicsOpacityEffect* effect = new QGraphicsOpacityEffect(currentWidget);
    currentWidget->setGraphicsEffect(effect);

    QPropertyAnimation* fadeOut = new QPropertyAnimation(effect, "opacity");
    fadeOut->setDuration(150);
    fadeOut->setStartValue(1.0);
    fadeOut->setEndValue(0.0);

    connect(fadeOut, &QPropertyAnimation::finished, [this, index, effect]() {
        stackedWidget->setCurrentIndex(index);

        QWidget* newWidget = stackedWidget->currentWidget();
        QGraphicsOpacityEffect* newEffect = new QGraphicsOpacityEffect(newWidget);
        newWidget->setGraphicsEffect(newEffect);

        QPropertyAnimation* fadeIn = new QPropertyAnimation(newEffect, "opacity");
        fadeIn->setDuration(150);
        fadeIn->setStartValue(0.0);
        fadeIn->setEndValue(1.0);
        fadeIn->start(QPropertyAnimation::DeleteWhenStopped);

        effect->deleteLater();
    });

    fadeOut->start(QPropertyAnimation::DeleteWhenStopped);
}

QWidget* MainWindow::createDashboardPage()
{
    // Outer container that holds the animated background
    QWidget* content = new QWidget();
    content->setStyleSheet("background: transparent;");

    // Stack layout so GIF sits behind content
    QVBoxLayout* stack = new QVBoxLayout(content);
    stack->setSpacing(0);
    stack->setContentsMargins(0, 0, 0, 0);

    // ── Animated GIF background label ──────────────────────────────────
    QLabel* bgLabel = new QLabel(content);
    bgLabel->setObjectName("dashboardBg");
    bgLabel->setScaledContents(true);
    bgLabel->setAlignment(Qt::AlignCenter);

    QMovie* bgMovie = new QMovie(":/images/images/dashboard_bg.gif", QByteArray(), bgLabel);
    if (bgMovie->isValid()) {
        bgLabel->setMovie(bgMovie);
        bgMovie->start();
    } else {
        // Fallback solid color
        bgLabel->setStyleSheet("background-color: #F0F4F8;");
    }

    // Make bgLabel fill the whole page by resizing with parent
    bgLabel->setGeometry(0, 0, content->width(), content->height());

    // Install resize event to keep bg filling the widget
    class BgResizeFilter : public QObject {
        QLabel* bg;
    public:
        BgResizeFilter(QLabel* label, QObject* parent) : QObject(parent), bg(label) {}
        bool eventFilter(QObject* obj, QEvent* ev) override {
            if (ev->type() == QEvent::Resize) {
                QWidget* w = qobject_cast<QWidget*>(obj);
                if (w) bg->setGeometry(0, 0, w->width(), w->height());
            }
            return QObject::eventFilter(obj, ev);
        }
    };
    content->installEventFilter(new BgResizeFilter(bgLabel, content));

    // ── Overlay card for text ──────────────────────────────────────────
    QWidget* overlay = new QWidget(content);
    overlay->setStyleSheet("background: transparent;");

    QVBoxLayout* layout = new QVBoxLayout(overlay);
    layout->setSpacing(20);
    layout->setContentsMargins(40, 40, 40, 40);
    layout->addStretch(1);

    // Glass card — use object name so only the frame itself gets the border/bg
    QFrame* card = new QFrame(overlay);
    card->setObjectName("dashCard");
    card->setStyleSheet(R"(
        QFrame#dashCard {
            background: rgba(15, 30, 70, 0.55);
            border-radius: 20px;
            border: 1px solid rgba(255, 255, 255, 0.25);
        }
        QFrame#dashCard * {
            background: transparent;
            border: none;
        }
    )");

    QGraphicsDropShadowEffect* shadow = new QGraphicsDropShadowEffect(card);
    shadow->setBlurRadius(40);
    shadow->setColor(QColor(0, 0, 0, 100));
    shadow->setOffset(0, 10);
    card->setGraphicsEffect(shadow);

    QVBoxLayout* cardLayout = new QVBoxLayout(card);
    cardLayout->setSpacing(8);
    cardLayout->setContentsMargins(40, 30, 40, 30);

    QLabel* title = new QLabel("Tableau de Bord");
    QFont titleFont("Segoe UI", 34, QFont::Bold);
    title->setFont(titleFont);
    title->setStyleSheet("color: white; background: transparent; border: none;");
    cardLayout->addWidget(title);

    // Subtle divider
    QFrame* divider = new QFrame(card);
    divider->setFrameShape(QFrame::HLine);
    divider->setStyleSheet("background: rgba(255,255,255,0.3); border: none; max-height: 1px;");
    divider->setFixedHeight(1);
    cardLayout->addWidget(divider);

    QString welcomeText = loggedUserName.isEmpty() ? "Bienvenue sur PortFlow" : "Bienvenue, " + loggedUserName;
    if (!loggedUserRole.isEmpty()) welcomeText += " (" + loggedUserRole + ")";

    welcomeLabel = new QLabel(welcomeText);
    QFont subtitleFont("Segoe UI", 14);
    welcomeLabel->setFont(subtitleFont);
    welcomeLabel->setStyleSheet("color: rgba(200, 220, 255, 0.95); background: transparent; border: none;");
    cardLayout->addWidget(welcomeLabel);

    layout->addWidget(card, 0, Qt::AlignLeft | Qt::AlignBottom);
    layout->addStretch(0);

    // Overlay fills the whole page
    class OverlayResizeFilter : public QObject {
        QWidget* ov;
    public:
        OverlayResizeFilter(QWidget* overlay, QObject* parent) : QObject(parent), ov(overlay) {}
        bool eventFilter(QObject* obj, QEvent* ev) override {
            if (ev->type() == QEvent::Resize) {
                QWidget* w = qobject_cast<QWidget*>(obj);
                if (w) ov->setGeometry(0, 0, w->width(), w->height());
            }
            return QObject::eventFilter(obj, ev);
        }
    };
    content->installEventFilter(new OverlayResizeFilter(overlay, content));
    overlay->setGeometry(0, 0, content->width(), content->height());
    overlay->raise();

    return content;
}

void MainWindow::onNavigateToDashboard()
{
    setActiveButton(dashboardBtn);
    switchPage(0);
}

void MainWindow::onNavigateToEmployees()
{
    setActiveButton(employeesBtn);
    if (!employeePage) {
        EmployeeWindow* empWindow = new EmployeeWindow();
        empWindow->hide();
        QWidget* centralWidget = empWindow->centralWidget();
        QHBoxLayout* hLayout = qobject_cast<QHBoxLayout*>(centralWidget->layout());
        if (hLayout && hLayout->count() >= 2) {
            QLayoutItem* contentItem = hLayout->itemAt(1);
            if (contentItem) {
                employeePage = contentItem->widget();
                if (employeePage) {
                    employeePage->setParent(nullptr);
                    stackedWidget->addWidget(employeePage);
                }
            }
        }
    }
    if (employeePage) {
        updateThemeRecursive(employeePage, isDarkMode);
        translateRecursive(employeePage, isEnglish);
        switchPage(stackedWidget->indexOf(employeePage));
    }
}

void MainWindow::onNavigateToFrigos()
{
    setActiveButton(frigosBtn);
    if (!frigoPage) {
        FrigoWindow* frigoWindow = new FrigoWindow();
        frigoWindow->hide();
        QWidget* centralWidget = frigoWindow->centralWidget();
        QHBoxLayout* hLayout = qobject_cast<QHBoxLayout*>(centralWidget->layout());
        if (hLayout && hLayout->count() >= 2) {
            QLayoutItem* contentItem = hLayout->itemAt(1);
            if (contentItem) {
                frigoPage = contentItem->widget();
                if (frigoPage) {
                    frigoPage->setParent(nullptr);
                    stackedWidget->addWidget(frigoPage);
                }
            }
        }
    }
    if (frigoPage) {
        updateThemeRecursive(frigoPage, isDarkMode);
        translateRecursive(frigoPage, isEnglish);
        switchPage(stackedWidget->indexOf(frigoPage));
    }
}

void MainWindow::updateFrigoNotifications()
{
    if (frigoNotifyLabel1) frigoNotifyLabel1->setVisible(currentlyInDanger.contains("FRG-001"));
    if (frigoNotifyLabel2) frigoNotifyLabel2->setVisible(currentlyInDanger.contains("FRG-002"));
}

void MainWindow::onNavigateToPeches()
{
    setActiveButton(pechesBtn);
    if (!pechePage) {
        PecheWindow* pecheWindow = new PecheWindow();
        pecheWindow->hide();
        QWidget* centralWidget = pecheWindow->centralWidget();
        QHBoxLayout* hLayout = qobject_cast<QHBoxLayout*>(centralWidget->layout());
        if (hLayout && hLayout->count() >= 2) {
            QLayoutItem* contentItem = hLayout->itemAt(1);
            if (contentItem) {
                pechePage = contentItem->widget();
                if (pechePage) {
                    pechePage->setParent(nullptr);
                    stackedWidget->addWidget(pechePage);
                }
            }
        }
    }
    if (pechePage) {
        updateThemeRecursive(pechePage, isDarkMode);
        translateRecursive(pechePage, isEnglish);
        switchPage(stackedWidget->indexOf(pechePage));
    }
}

void MainWindow::onNavigateToBateaux()
{
    setActiveButton(bateauxBtn);
    if (!bateauPage) {
        BateauWindow* batWindow = new BateauWindow();
        batWindow->hide();
        QWidget* centralWidget = batWindow->centralWidget();
        QHBoxLayout* hLayout = qobject_cast<QHBoxLayout*>(centralWidget->layout());
        if (hLayout && hLayout->count() >= 2) {
            QLayoutItem* contentItem = hLayout->itemAt(1);
            if (contentItem) {
                bateauPage = contentItem->widget();
                if (bateauPage) {
                    bateauPage->setParent(nullptr);
                    stackedWidget->addWidget(bateauPage);
                }
            }
        }
    }
    if (bateauPage) {
        updateThemeRecursive(bateauPage, isDarkMode);
        translateRecursive(bateauPage, isEnglish);
        switchPage(stackedWidget->indexOf(bateauPage));
    }
}

void MainWindow::onNavigateToLivraison()
{
    setActiveButton(livraisonBtn);
    if (!livraisonPage) {
        LivraisonWindow* livWindow = new LivraisonWindow();
        livWindow->hide();
        QWidget* central = livWindow->centralWidget();
        if (central) {
            livraisonPage = central;
            livraisonPage->setParent(nullptr);
            stackedWidget->addWidget(livraisonPage);
        }
    }
    if (livraisonPage) {
        updateThemeRecursive(livraisonPage, isDarkMode);
        translateRecursive(livraisonPage, isEnglish);
        switchPage(stackedWidget->indexOf(livraisonPage));
    }
}

void MainWindow::onNavigateToQuais()
{
    setActiveButton(quaisBtn);
    if (!quaisPage) {
        QuaisWindow* qWindow = new QuaisWindow();
        qWindow->hide();
        QWidget* central = qWindow->centralWidget();
        QHBoxLayout* hLayout = qobject_cast<QHBoxLayout*>(central->layout());
        if (hLayout && hLayout->count() >= 2) {
            QLayoutItem* contentItem = hLayout->itemAt(1);
            if (contentItem) {
                quaisPage = contentItem->widget();
                if (quaisPage) {
                    quaisPage->setParent(nullptr);
                    stackedWidget->addWidget(quaisPage);
                }
            }
        }
    }
    if (quaisPage) {
        updateThemeRecursive(quaisPage, isDarkMode);
        translateRecursive(quaisPage, isEnglish);
        switchPage(stackedWidget->indexOf(quaisPage));
    }
}

void MainWindow::onLogout()
{
    if (QMessageBox::question(this, "Déconnexion", "Voulez-vous vraiment vous déconnecter ?", QMessageBox::Yes | QMessageBox::No) == QMessageBox::Yes) {
        LoginWindow* loginWindow = new LoginWindow();
        loginWindow->show();
        this->close();
    }
}

void MainWindow::toggleGlobalTheme()
{
    isDarkMode = !isDarkMode;
    qApp->setProperty("isDarkMode", isDarkMode);
    updateThemeRecursive(this, isDarkMode);
}


void MainWindow::onSettingsClicked()
{
    QDialog* settingsDlg = new QDialog(this);
    settingsDlg->setWindowTitle("Paramètres - PortFlow");
    settingsDlg->setFixedSize(500, 600);
    
    // Set solid background for the settings dialog
    settingsDlg->setStyleSheet(isDarkMode ? 
        "QDialog { background-color: #1A202C; }" : 
        "QDialog { background-color: #FFFFFF; }");

    QVBoxLayout* mainLay = new QVBoxLayout(settingsDlg);
    mainLay->setContentsMargins(0, 0, 0, 0);

    // Main container Card
    QFrame* glassCard = new QFrame();
    glassCard->setObjectName("glassCard");
    glassCard->setStyleSheet("QFrame#glassCard { background-color: transparent; border: none; }");
    mainLay->addWidget(glassCard);

    QVBoxLayout* layout = new QVBoxLayout(glassCard);
    layout->setSpacing(25);
    layout->setContentsMargins(40, 40, 40, 40);

    // Title
    QLabel* title = new QLabel(isEnglish ? "Settings" : "Paramètres");
    title->setFont(QFont("Segoe UI", 22, QFont::Bold));
    title->setStyleSheet("color: #2B5EA6; background: transparent;");
    title->setAlignment(Qt::AlignCenter);
    layout->addWidget(title);

    // Style for buttons
    auto btnStyle = R"(
        QPushButton {
            background-color: #2B5EA6;
            color: white;
            border: none;
            border-radius: 12px;
            padding: 18px;
            font-weight: bold;
            font-size: 15px;
        }
        QPushButton:hover {
            background-color: #15305b;
        }
    )";

    // Language Section
    QPushButton* langBtnDlg = new QPushButton(isEnglish ? "🌐  Language: English" : "🌐  Langue: Français");
    langBtnDlg->setStyleSheet(btnStyle);
    layout->addWidget(langBtnDlg);

    // Theme Section (Dark/Light Mode)
    QPushButton* darkBtnDlg = new QPushButton(isDarkMode ? "☀️  Mode: Light (Clair)" : "🌙  Mode: Dark (Sombre)");
    darkBtnDlg->setStyleSheet(btnStyle);
    layout->addWidget(darkBtnDlg);

    // Connections
    connect(langBtnDlg, &QPushButton::clicked, [this, langBtnDlg, settingsDlg]() {
        toggleLanguage();
        langBtnDlg->setText(isEnglish ? "🌐  Language: English" : "🌐  Langue: Français");
        translateRecursive(settingsDlg, isEnglish);
    });

    connect(darkBtnDlg, &QPushButton::clicked, [this, darkBtnDlg, settingsDlg, glassCard]() {
        toggleGlobalTheme();
        darkBtnDlg->setText(isDarkMode ? "☀️  Mode: Light (Clair)" : "🌙  Mode: Dark (Sombre)");
        settingsDlg->setStyleSheet(isDarkMode ? 
            "QDialog { background-color: #1A202C; }" : 
            "QDialog { background-color: #FFFFFF; }");
    });

    layout->addStretch();

    QPushButton* closeBtn = new QPushButton(isEnglish ? "Close" : "Fermer");
    closeBtn->setStyleSheet("background-color: #A0AEC0; color: white; border-radius: 10px; padding: 12px; font-weight: bold;");
    connect(closeBtn, &QPushButton::clicked, settingsDlg, &QDialog::accept);
    layout->addWidget(closeBtn);

    translateRecursive(settingsDlg, isEnglish);
    settingsDlg->exec();
}

void MainWindow::updateThemeRecursive(QWidget* widget, bool isDark)
{
    if (!widget) return;
    QVariant origVar = widget->property("origStyleSheet");
    if (!origVar.isValid()) {
        origVar = widget->styleSheet();
        widget->setProperty("origStyleSheet", origVar);
    }
    QString style = origVar.toString();
    if (!style.isEmpty()) {
        if (isDark) {
            style.replace("#1e3a5f", "#F7FAFC", Qt::CaseInsensitive);
            style.replace("#2C3E50", "#F7FAFC", Qt::CaseInsensitive);
            style.replace("#6B7280", "#A0AEC0", Qt::CaseInsensitive);
            style.replace("#1f2937", "#F7FAFC", Qt::CaseInsensitive);
            style.replace("#0f172a", "#F7FAFC", Qt::CaseInsensitive);
            style.replace("#334155", "#F7FAFC", Qt::CaseInsensitive);
            style.replace("#64748b", "#A0AEC0", Qt::CaseInsensitive);
            style.replace("#1e293b", "#F7FAFC", Qt::CaseInsensitive);
            style.replace("#374151", "#F7FAFC", Qt::CaseInsensitive);
            style.replace("#4B5563", "#F7FAFC", Qt::CaseInsensitive);
            
            style.replace("#F0F4F8", "#1A202C", Qt::CaseInsensitive);
            style.replace("#f8fafc", "#1A202C", Qt::CaseInsensitive);
            style.replace("#F9FAFB", "#2D3748", Qt::CaseInsensitive);
            style.replace("#f1f5f9", "#2D3748", Qt::CaseInsensitive);
            
            style.replace("background-color: white", "background-color: #2D3748", Qt::CaseInsensitive);
            style.replace("background-color:white", "background-color: #2D3748", Qt::CaseInsensitive);
            style.replace("background: white", "background: #2D3748", Qt::CaseInsensitive);
            style.replace("background:white", "background: #2D3748", Qt::CaseInsensitive);
            
            style.replace("#FFFFFF", "#2D3748", Qt::CaseInsensitive);
            style.replace("#CBD5E1", "#4A5568", Qt::CaseInsensitive);
            style.replace("#e2e8f0", "#4A5568", Qt::CaseInsensitive);
            style.replace("#d1d5db", "#4A5568", Qt::CaseInsensitive);
            style.replace("color: black", "color: white", Qt::CaseInsensitive);
            style.replace("color:black", "color:white", Qt::CaseInsensitive);

            style.replace("background-color: #EBF5FF; color: #2563EB;", "background-color: #2B6CB0; color: white;", Qt::CaseInsensitive);
            style.replace("background-color:#EBF5FF;color:#2563EB;", "background-color:#2B6CB0;color:white;", Qt::CaseInsensitive);
            style.replace("selection-background-color: #eff6ff;", "selection-background-color: #2B6CB0;", Qt::CaseInsensitive);
            style.replace("selection-background-color:#eff6ff;", "selection-background-color:#2B6CB0;", Qt::CaseInsensitive);
        }
        widget->setStyleSheet(style);
    }
    // Use a copy of the children list to prevent SEGFAULT when setStyleSheet mutates widget children list
    const QObjectList childrenList = widget->children();
    for (QObject* child : childrenList) {
        if (QWidget* w = qobject_cast<QWidget*>(child)) {
            updateThemeRecursive(w, isDark);
        }
    }
}

void MainWindow::toggleLanguage()
{
    isEnglish = !isEnglish;
    qApp->setProperty("isEnglish", isEnglish);
    translateRecursive(this, isEnglish);
}

void MainWindow::translateRecursive(QWidget* widget, bool toEnglish)
{
    if (!widget) return;
    auto translateText = [toEnglish](QString& text) {
        if (text.isEmpty()) return;
        static const QList<QPair<QString, QString>> dict = {
            {"Alertes opérationnelles generees a partir de l'analyse d'occupation des quais, via regles locales et moteur AI/API si configure.", "Operational alerts generated from dock occupancy analysis, via local rules and AI/API engine if configured."},
            {"Sélectionnez un quai pour générer son contrat de location :", "Select a dock to generate its rental contract:"},
            {"Module d'Analyse Continue de l'Utilisation des Quais", "Continuous Dock Utilization Analysis Module"},
            {"🚢  Enregistrement d'un nouveau navire au registre", "🚢  Registration of a new vessel in the registry"},
            {"Historique des captures et affectations de stockage", "Catch history and storage assignments"},
            {"✏️  Mise à jour des spécifications techniques", "✏️  Technical specifications update"},
            {"Administration des emplacements et disponibilités", "Location and availability administration"},
            {"Administration du personnel et suivi des rôles", "Staff administration and role tracking"},
            {"Suivi des expéditions de poisson et logistique", "Shipment tracking and logistics"},
            {"Surveillance des stocks froids et températures", "Monitoring of cold stocks and temperatures"},
            {"Tableau de Bord - Statistiques des Livraisons", "Dashboard - Delivery Statistics"},
            {"Contrôle thermique et stockage des poissons", "Temperature control and fish storage"},
            {"Vue d'ensemble de l'utilisation des quais...", "Overview of dock utilization..."},
            {"Tableau de Bord - Statistiques de la Flotte", "Dashboard - Fleet Statistics"},
            {"Tableau de Bord - Statistiques des Pêches", "Dashboard - Fishing Statistics"},
            {"Rechercher par catégorie, référence...", "Search by category, reference..."},
            {"Tableau de Bord - Statistiques des Frigos", "Dashboard - Fridge Statistics"},
            {"Coordination des transports et logistique", "Transport and logistics coordination"},
            {"Journal des captures, lots et catégories", "Log of catches, batches and categories"},
            {"Rechercher par date, adresse ou statut...", "Search by date, address or status..."},
            {"Génération du rapport intelligent pour ", "Generating smart report for "},
            {"Rechercher par nom ou immatriculation...", "Search by name or registration..."},
            {"Rechercher un employé par nom, poste...", "Search employee by name, role..."},
            {"Tableau de Bord - Statistiques Employés", "Dashboard - Employee Statistics"},
            {"Rechercher un quai par numéro, type...", "Search for a dock by number, type..."},
            {"Analyse des Unités de Réfrigération", "Refrigeration Units Analysis"},
            {"Suivi de la flotte et des maintenances", "Fleet and maintenance tracking"},
            {"Fréquence des sorties\\n(Automatique):", "Exit frequency\\n(Automatic):"},
            {"Analyse de la Production Halieutique", "Fishery Production Analysis"},
            {"Répartition Heures Supplémentaires", "Overtime Hours Distribution"},
            {"Aucun avertissement pour le moment.", "No warnings at the moment."},
            {"OK - Pas de maintenance nécessaire", "OK - No maintenance needed"},
            {"Insights Stratégiques (Google AI)", "Strategic Insights (Google AI)"},
            {"Guide de Classification - PortFlow", "Classification Guide - PortFlow"},
            {"Distribution du Poids par Espèce", "Weight Distribution by Species"},
            {"Utilisation par Type de Véhicule", "Usage by Vehicle Type"},
            {"PortFlow - Gestion des Livraisons", "PortFlow - Delivery Management"},
            {"Rapport Intelligent IA - PortFlow", "Smart AI Report - PortFlow"},
            {"Analyse Predictive & Performance", "Predictive Analysis & Performance"},
            {"Analyse Prédictive & Performance", "Predictive Analysis & Performance"},
            {"Rechercher par statut, contenu...", "Search by status, content..."},
            {"Format Q-[Lettre][Chiffre] requis", "Format Q-[Letter][Digit] required"},
            {"Répartition par Type de Poisson", "Distribution by Fish Type"},
            {"Utilisation Globale de Capacité", "Global Capacity Usage"},
            {"Prochaine maintenance estimée :", "Estimated next maintenance:"},
            {"PortFlow - Gestion des Employés", "PortFlow - Employee Management"},
            {"Répartition par Disponibilité", "Distribution by Availability"},
            {"Analyse de l'IA (Google Gemini)", "AI Analysis (Google Gemini)"},
            {"Avertissements de surveillance", "Monitoring Warnings"},
            {"PortFlow - Gestion des Bateaux", "PortFlow - Boat Management"},
            {"PortFlow - Gestion des Pêches", "PortFlow - Fishing Management"},
            {"PortFlow - Gestion des Frigos", "PortFlow - Fridge Management"},
            {"Règlement Intérieur du Port", "Internal Regulations of the Port"},
            {"Recommandations Stratégiques", "Strategic Recommendations"},
            {"DATE DE DERNIÈRE MAINTENANCE", "LAST MAINTENANCE DATE"},
            {"Analyse des Flux Logistiques", "Logistics Flow Analysis"},
            {"PortFlow - Gestion des Quais", "PortFlow - Dock Management"},
            {"Demande de Congé Générée", "Leave Request Generated"},
            {"Durée de location (jours) *", "Rental duration (days) *"},
            {"Un entier positif est requis", "A positive integer is required"},
            {"Remarques avant Exportation", "Remarks before Export"},
            {"Nouveau contrat de location", "New rental contract"},
            {"Disponibilité des Bateaux", "Boat Availability"},
            {"Employés par Département", "Employees by Department"},
            {"Masse Salariale par Année", "Payroll by Year"},
            {"Prédiction de Maintenance", "Maintenance Prediction"},
            {"➕  Enregistrer le Navire", "➕  Save Vessel"},
            {"Vos Remarques (Éditable)", "Your Remarks (Editable)"},
            {"Disponibilité des Frigos", "Fridge Availability"},
            {"Surveillance recommandée", "Monitoring recommended"},
            {"Statistiques des Bateaux", "Boat Statistics"},
            {"Volume Total par Espèce", "Total Volume by Species"},
            {"Statistiques Générales", "General Statistics"},
            {"Mois depuis maintenance:", "Months since maintenance:"},
            {"CODE SECRET (4 CHIFFRES)", "SECRET CODE (4 DIGITS)"},
            {"Affecter automatiquement", "Assign automatically"},
            {"Mimumum 2 lettres requis", "Minimum 2 letters required"},
            {"Format TN-YYYY-ID requis", "Format TN-YYYY-ID required"},
            {"PROPRIÉTAIRE / EMPLOYÉ", "OWNER / EMPLOYEE"},
            {"Prochaine Maint. (Est.)", "Next Maint. (Est.)"},
            {"Système de Prédiction", "Prediction System"},
            {"Mois depuis maintenance", "Months since maintenance"},
            {"Exporter un contrat PDF", "Export a PDF contract"},
            {"Fréquence des sorties", "Exit frequency"},
            {"Annuler (Choisir date)", "Cancel (Choose date)"},
            {"Résultat de l'analyse", "Analysis result"},
            {"Répartition par État", "Distribution by State"},
            {"Consultation IA Google", "Google AI Consultation"},
            {"Attestation de Travail", "Work Certificate"},
            {"Paramètres - PortFlow", "Settings - PortFlow"},
            {"Bienvenue sur PortFlow", "Welcome to PortFlow"},
            {"Statistiques des Quais", "Dock Statistics"},
            {"Gestion des Livraisons", "Delivery Management"},
            {"Efficacité (Livrées)", "Efficiency (Delivered)"},
            {"Aucun quai disponible.", "No dock available."},
            {"Statut des Livraisons", "Delivery Status"},
            {"Maintenance urgente !", "Urgent maintenance!"},
            {"Nombre d'Utilisations", "Number of Uses"},
            {"Gestion des Employés", "Employee Management"},
            {"Dernière Maintenance", "Last Maintenance"},
            {"Dernière maintenance", "Last maintenance"},
            {"Règlement Intérieur", "Internal Regulation"},
            {"Disponibilite du quai", "Dock Availability"},
            {"Exactement 4 chiffres", "Exactly 4 digits"},
            {"Nombre positif requis", "Positive number required"},
            {"Analyse de la Flotte", "Fleet Analysis"},
            {"Insights IA (Google)", "AI Insights (Google)"},
            {"Analyse Structurelle", "Structural Analysis"},
            {"Options d'Export PDF", "PDF Export Options"},
            {"ÂGE DU BATEAU (ans)", "BOAT AGE (years)"},
            {"Générer le contrat", "Generate contract"},
            {"💾  Mettre à jour", "💾  Update"},
            {"Mode: Light (Clair)", "Mode: Light"},
            {"Mode: Dark (Sombre)", "Mode: Dark"},
            {"Date ↑ (ancienne)", "Date ↑ (old)"},
            {"Date ↓ (récente)", "Date ↓ (new)"},
            {"Analyse IA en cours", "AI Analysis in progress"},
            {"Gestion des Bateaux", "Boat Management"},
            {"Gestion des Pêches", "Fishing Management"},
            {"Statut d'Occupation", "Occupation Status"},
            {"Enregistrer le Quai", "Save Dock"},
            {"Catégorie (A→Z)", "Category (A→Z)"},
            {"Catégorie (Z→A)", "Category (Z→A)"},
            {"Nouvelle Livraison", "New Delivery"},
            {"Durée de location", "Rental duration"},
            {"Gestion des Frigos", "Fridge Management"},
            {"Export Rapport PDF", "Export PDF Report"},
            {"Modifier le Bateau", "Edit the Boat"},
            {"Taux Absentéisme", "Absenteeism Rate"},
            {"Taux d'Occupation", "Occupancy Rate"},
            {"Langue: Français", "Language: French"},
            {"Language: English", "Language: English"},
            {"Demande de Congé", "Leave Request"},
            {"Rapport Présence", "Attendance Report"},
            {"Gestion des Quais", "Dock Management"},
            {"Analyse complète", "Complete Analysis"},
            {"CHOISIR LE BATEAU", "CHOOSE BOAT"},
            {"Capacité Max (T)", "Max Capacity (T)"},
            {"Tarif de Location", "Rental Rate"},
            {"Total Livraisons", "Total Deliveries"},
            {"Capacité Totale", "Total Capacity"},
            {"Register Face ID", "Register Face ID"},
            {"Modifier le Quai", "Edit the Dock"},
            {"Date de début *", "Start date *"},
            {"Longueur Max (m)", "Max Length (m)"},
            {"Âge du bateau:", "Boat age:"},
            {"Nouvelle date :", "New date:"},
            {"Non disponibles", "Unavailable"},
            {"Total Employés", "Total Employees"},
            {"Résumé Global", "Global Summary"},
            {"Recommandations", "Recommendations"},
            {"sorties (Total)", "departures (Total)"},
            {"Tableau de Bord", "Dashboard"},
            {"Tableau de bord", "Dashboard"},
            {"Langue: English", "Language: English"},
            {"Nouvel Employé", "New Employee"},
            {"Immatriculation", "Registration"},
            {"Ajouter un Quai", "Add a Dock"},
            {"Planning Flotte", "Fleet Schedule"},
            {"IMMATRICULATION", "REGISTRATION"},
            {"Modifier Bateau", "Edit Boat"},
            {"Âge du bateau", "Boat age"},
            {"Non disponible", "Unavailable"},
            {"Nombre de Lots", "Number of Batches"},
            {"Taux Livraison", "Delivery Rate"},
            {"Disponibilité", "Availability"},
            {"Nouveau Bateau", "New Boat"},
            {"Tarif / Durée", "Rate / Duration"},
            {"Quantité (Kg)", "Quantity (Kg)"},
            {"Quantité (kg)", "Quantity (kg)"},
            {"Administration", "Administration"},
            {"Recommandation", "Recommendation"},
            {"Ajouter Bateau", "Add Boat"},
            {"Profondeur (m)", "Depth (m)"},
            {"Tarif par jour", "Daily rate"},
            {"État actuel:", "Current state:"},
            {"Total Unités", "Total Units"},
            {"Total bateaux", "Total boats"},
            {"Nouveau Frigo", "New Fridge"},
            {"Ajouter un Frigo", "Add a Fridge"},
            {"Modifier le Frigo", "Edit the Fridge"},
            {"➕  Activer Frigo", "➕  Activate Fridge"},
            {"DESTINATION DE STOCKAGE (FRIGO)", "STORAGE DESTINATION (FRIDGE)"},
            {"Générer PDF", "Generate PDF"},
            {"Modifier Quai", "Edit Dock"},
            {"Préférences", "Preferences"},
            {"CAPACITÉ (T)", "CAPACITY (T)"},
            {"Scanner Carte", "Scan Card"},
            {"NOM DU BATEAU", "BOAT NAME"},
            {"Nom du navire", "Vessel name"},
            {"QUAI AFFECTÉ", "ASSIGNED DOCK"},
            {"Capacité max", "Max capacity"},
            {"Ok (Valider)", "Ok (Confirm)"},
            {"État actuel", "Current state"},
            {"Types Actifs", "Active Types"},
            {"Volume Total", "Total Volume"},
            {"Nouveau Quai", "New Dock"},
            {"Exporter PDF", "Export PDF"},
            {"Statistiques", "Statistics"},
            {"Localisation", "Location"},
            {"Tarif (DT/j)", "Rate (DT/d)"},
            {"Température", "Temperature"},
            {"LONGUEUR (m)", "LENGTH (m)"},
            {"Indisponible", "Unavailable"},
            {"ÉTAT ACTUEL", "CURRENT STATE"},
            {"Code du Quai", "Dock Code"},
            {"Type de Quai", "Dock Type"},
            {"Code du quai", "Dock code"},
            {"Type du quai", "Dock type"},
            {"Ex: Marchand", "Ex: Merchant"},
            {"Longueur max", "Max length"},
            {"Décision :", "Decision:"},
            {"Disponibles", "Available"},
            {"Trier par :", "Sort by :"},
            {"Par défaut", "Default"},
            {"Maintenance", "Maintenance"},
            {"Nom du Quai", "Dock Name"},
            {"Code Secret", "Secret Code"},
            {"Destination", "Destination"},
            {"Paramètres", "Settings"},
            {"Enregistrer", "Save"},
            {"Mètres (m)", "Meters (m)"},
            {"Âge Moyen", "Average Age"},
            {"Poids (Kg)", "Weight (Kg)"},
            {"Disponible", "Available"},
            {"Nom Bateau", "Boat Name"},
            {"Catégorie", "Category"},
            {"Avancement", "Progress"},
            {"Occupation", "Occupation"},
            {"Date Rés.", "Res. Date"},
            {"Employé: ", "Employee: "},
            {"Tonnes (T)", "Tons (T)"},
            {"Aucun quai", "No dock"},
            {"Profondeur", "Depth"},
            {"Quantité", "Quantity"},
            {"Employés", "Employees"},
            {"Livraison", "Delivery"},
            {"Confirmer", "Confirm"},
            {"DT / Jour", "DT / Day"},
            {"Espèces", "Species"},
            {"Employé", "Employee"},
            {"Durée *", "Duration *"},
            {"PÉRIODE", "PERIOD"},
            {"Terminer", "Finish"},
            {"Ex: 1234", "Ex: 1234"},
            {"Ex: 12.5", "Ex: 12.5"},
            {"Ex: Q-A1", "Ex: Q-A1"},
            {"Bateaux", "Boats"},
            {"Quitter", "Quit"},
            {"Annuler", "Cancel"},
            {"Prénom", "First Name"},
            {"Salaire", "Salary"},
            {"Poisson", "Fish"},
            {"Livreur", "Driver"},
            {"Actions", "Actions"},
            {"Occupé", "Occupied"},
            {"État *", "State *"},
            {"Auto-AI", "Auto-AI"},
            {"Fermer", "Close"},
            {"Statut", "Status"},
            {"Bateau", "Boat"},
            {"Pêche", "Fishing"},
            {"Frigos", "Fridges"},
            {"R.A.S.", "O.K."},
            {"Frigo", "Fridge"},
            {"Quais", "Docks"},
            {"Ex: 5", "Ex: 5"},
            {"Quai", "Dock"},
            {"Date", "Date"},
            {"Nom", "Last Name"},
            {"➕  Nouveau Lot", "➕  New Lot"},
            {"Nouveau Lot de Pêche", "New Fishing Lot"},
            {"Modifier Lot de Pêche", "Edit Fishing Lot"},
            {"Ajouter un Lot", "Add a Lot"},
            {"🎣  Enregistrement d'une nouvelle prise en mer", "🎣  Recording of a new catch at sea"},
            {"✏️  Modification des données de capture", "✏️  Modification of catch data"},
            {"➕  Enregistrer le Lot", "➕  Save Lot"},
            {"RÉFÉRENCE DU LOT", "LOT REFERENCE"},
            {"ESPÈCE", "SPECIES"},
            {"QUANTITÉ (Kg)", "QUANTITY (Kg)"},
            {"DATE DE CAPTURE", "CATCH DATE"},
            {"BATEAU D'ORIGINE", "ORIGIN BOAT"},
            {"PÊCHEUR RESPONSABLE", "RESPONSIBLE FISHERMAN"},
            {"🧊  Installation d'une nouvelle unité de stockage à froid", "🧊  Installation of a new cold storage unit"},
            {"✏️  Mise à jour des paramètres de conservation", "✏️  Updating conservation parameters"},
            {"RÉFÉRENCE UNITÉ (FRG-XXXX)", "UNIT REFERENCE (FRG-XXXX)"},
            {"CAPACITÉ MAX (Kg)", "MAX CAPACITY (Kg)"},
            {"TEMPÉRATURE (°C)", "TEMPERATURE (°C)"},
            {"STATUT", "STATUS"},
            {"TYPE DE POISSON", "FISH TYPE"},
            {"DATE DE RÉSERVATION / MISE EN SERVICE", "RESERVATION DATE / COMMISSIONING"},
            {"OCCUPATION ACTUELLE (Kg)", "CURRENT OCCUPATION (Kg)"},
            {"TÉLÉPHONE RESPONSABLE", "RESPONSIBLE PHONE"},
            {"Format invalide — ex: FRG-001", "Invalid format — ex: FRG-001"},
            {"Nombre requis (ex: -20.0)", "Number required (ex: -20.0)"},
            {"0 à %1 Kg requis", "0 to %1 Kg required"},
            {"Nombre ≥ 0 requis", "Number ≥ 0 required"},
            {"📦 Espace dans", "📦 Space in"},
            {"libres", "free"},
            {"Format REF-YYYY-ID requis", "Format REF-YYYY-ID required"},
            {"Saisissez une quantité pour l'IA.", "Enter a quantity for AI."},
            {"Sélectionnez une espèce d'abord.", "Select a species first."},
            {"Aucun stockage optimal trouvé.", "No optimal storage found."}
        };
        for (const auto& pair : dict) {
            QString fr = pair.first; QString en = pair.second;
            if (toEnglish && text.contains(fr)) text.replace(fr, en);
            else if (!toEnglish && text.contains(en)) text.replace(en, fr);
        }
    };

    // Translate the window title if it matches a dictionary entry
    QString title = widget->windowTitle();
    if (!title.isEmpty()) {
        QString originalTitle = title;
        translateText(title);
        if (title != originalTitle) {
            widget->setWindowTitle(title);
        }
    }

    if (QLabel* lbl = qobject_cast<QLabel*>(widget)) {
        QString text = lbl->text(); translateText(text); lbl->setText(text);
    } else if (QPushButton* btn = qobject_cast<QPushButton*>(widget)) {
        QString text = btn->text(); translateText(text); btn->setText(text);
    } else if (QComboBox* combo = qobject_cast<QComboBox*>(widget)) {
        for (int i = 0; i < combo->count(); ++i) {
            QString text = combo->itemText(i);
            translateText(text);
            combo->setItemText(i, text);
        }
    } else if (QTableWidget* table = qobject_cast<QTableWidget*>(widget)) {
        for (int i = 0; i < table->columnCount(); ++i) {
            if (QTableWidgetItem* item = table->horizontalHeaderItem(i)) {
                QString text = item->text(); translateText(text); item->setText(text);
            }
        }
    } else if (QLineEdit* line = qobject_cast<QLineEdit*>(widget)) {
        QString text = line->placeholderText(); translateText(text); line->setPlaceholderText(text);
    }
    for (QObject* child : widget->children()) {
        if (QWidget* w = qobject_cast<QWidget*>(child)) {
            translateRecursive(w, toEnglish);
        } else if (QAction* act = qobject_cast<QAction*>(child)) {
            QString text = act->text();
            translateText(text);
            act->setText(text);
        }
    }
}

void MainWindow::checkMaintenanceAlerts() {
    QStringList boatNames = Bateau::getUpcomingMaintenanceAlerts();
    
    if (!boatNames.isEmpty()) {
        if (!trayIcon) {
            trayIcon = new QSystemTrayIcon(this);
            connect(trayIcon, &QSystemTrayIcon::messageClicked, this, &MainWindow::onTrayMessageClicked);
        }
        
        trayIcon->setIcon(QIcon(":/images/images/logo.png"));
        if (trayIcon->icon().isNull()) {
            trayIcon->setIcon(this->style()->standardIcon(QStyle::SP_MessageBoxWarning));
        }
        trayIcon->show();
        
        QString message = "Les bateaux suivants nécessitent une maintenance :\n" + boatNames.join("\n");
        trayIcon->showMessage("Alerte Maintenance", message, QSystemTrayIcon::Warning, 15000);
    }
}

void MainWindow::onTrayMessageClicked() {
    QStringList boatNames = Bateau::getUpcomingMaintenanceAlerts();
    if (boatNames.isEmpty()) return;

    QString detail = "Voici la liste détaillée des bateaux nécessitant une maintenance :\n\n";
    detail += boatNames.join("\n");
    detail += "\n\nVeuillez vérifier l'état de ces bateaux dans l'onglet 'Bateaux'.";

    QMessageBox::information(this, "PortFlow - Détails Maintenance", detail);
}

void MainWindow::handleSerialData()
{
    // Connection health check
    if (!A.getserial()->isOpen()) {
        static int openErrCount = 0;
        if (++openErrCount % 5 == 0) qDebug() << "CRITICAL: Serial port is CLOSED!";
    }

    QByteArray rawData = A.read_from_arduino();
    if (!rawData.isEmpty()) {
        qDebug() << "RAW SERIAL DATA RECEIVED:" << rawData;
    } else {
        static int waitCount = 0;
        if (++waitCount % 10 == 0) {
            qDebug() << "Monitoring Port:" << A.getarduino_port_name() 
                     << "| Bytes Available:" << A.getserial()->bytesAvailable()
                     << "| Is Open:" << A.getserial()->isOpen();
        }
    }
    serialBuffer += rawData;
    
    // 1. Process fridge messages (delimited by ;)
    while (serialBuffer.contains(';')) {
        int index = serialBuffer.indexOf(';');
        QByteArray message = serialBuffer.left(index).trimmed();
        serialBuffer.remove(0, index + 1);
        
        QString msgStr = QString::fromLatin1(message);
        qDebug() << "Fridge Data:" << msgStr;
        
        QRegularExpression re("(S[12]):(\\d+\\.?\\d*)");
        QRegularExpressionMatch match = re.match(msgStr);
        if (match.hasMatch()) {
            QString sensorIdStr = match.captured(1);
            double temp = match.captured(2).toDouble();
            checkFridgeTemperature((sensorIdStr == "S1") ? 1 : 2, temp);
        }
    }

    // 2. Process port access messages (delimited by #)
    while (serialBuffer.contains('#')) {
        int index = serialBuffer.indexOf('#');
        QString code = QString::fromLatin1(serialBuffer.left(index)).trimmed();
        serialBuffer.remove(0, index + 1);
        
        if (!code.isEmpty()) {
            processPortAccess(code);
        }
    }

    // 3. Process RFID messages (delimited by \n)
    while (serialBuffer.contains('\n')) {
        int index = serialBuffer.indexOf('\n');
        QString msgStr = QString::fromLatin1(serialBuffer.left(index)).trimmed();
        serialBuffer.remove(0, index + 1);
        
        if (!msgStr.isEmpty()) {
            qDebug() << "RFID/Arduino Line:" << msgStr;
            if (msgStr.startsWith("MAINTENANCE_QUAI:")) {
                bool ok = false;
                const int idQuai = msgStr.mid(QString("MAINTENANCE_QUAI:").length()).trimmed().toInt(&ok);
                if (ok) {
                    QuaisWindow::handleMaintenanceImpact(idQuai);
                } else {
                    qDebug() << "Invalid maintenance message:" << msgStr;
                }
            } else if (msgStr.contains("UID: ")) {
                int uidPos = msgStr.indexOf("UID: ") + 5;
                QString uid = msgStr.mid(uidPos).trimmed();
                emit rfidScanned(uid);
                processRFIDPresence(uid);
            }
        }
    }
}

void MainWindow::processPortAccess(const QString& code)
{
    qDebug() << "--- Accès Port (Simplifié) ---";
    
    QSqlQuery bQuery;
    // On cherche le bateau par son code secret
    bQuery.prepare("SELECT IDBATEAU, NOMBATEAU, ETAT, IDQUAI FROM BATEAUX WHERE CODE_SECRET = :code");
    bQuery.bindValue(":code", code.toInt());

    if (!bQuery.exec()) {
        QMessageBox::critical(this, "Erreur SQL", "Erreur lecture bateau : " + bQuery.lastError().text());
        return;
    }

    if (bQuery.next()) {
        int idBateau = bQuery.value(0).toInt();
        QString nomBateau = bQuery.value(1).toString();
        QString etatBateau = bQuery.value(2).toString();
        QVariant idQuaiActuel = bQuery.value(3);
        
        // [SÉCURITÉ] Si le bateau est déjà au port
        QString cleanEtat = etatBateau.trimmed().simplified();
        if (cleanEtat.compare("Au port", Qt::CaseInsensitive) == 0) {
            A.write_to_arduino("R\n");
            
            // On laisse 100ms au système pour envoyer le signal avant de bloquer avec la fenêtre
            QTimer::singleShot(100, this, [this, nomBateau](){
                QMessageBox::warning(this, "Accès Refusé", "Bateau déjà au port : " + nomBateau);
            });
            return; 
        }

        // CAS 2 : Recherche de quai libre
        QSqlQuery qQuery;
        qQuery.prepare("SELECT IDQUAI, NUMERO FROM QUAIS "
                       "WHERE (UPPER(TRIM(ETAT)) NOT IN ('OCCUPÉ', 'OCCUPE') OR ETAT IS NULL) "
                       "AND (UPPER(TRIM(ETAT)) <> 'MAINTENANCE' OR ETAT IS NULL) "
                       "AND ROWNUM <= 1");

        if (qQuery.exec()) {
            if (qQuery.next()) {
                int idQuaiLibre = qQuery.value(0).toInt();
                int numQuai = qQuery.value(1).toInt();

                // Envoie l'autorisation en priorité
                A.write_to_arduino("A:" + QByteArray::number(idQuaiLibre) + "\n");

                QSqlQuery upB, upQ;
                upB.prepare("UPDATE BATEAUX SET IDQUAI = :q, ETAT = 'Au port' WHERE IDBATEAU = :id");
                upB.bindValue(":q", idQuaiLibre);
                upB.bindValue(":id", idBateau);

                upQ.prepare("UPDATE QUAIS SET ETAT = 'Occupé' WHERE IDQUAI = :id");
                upQ.bindValue(":id", idQuaiLibre);

                if (upB.exec() && upQ.exec()) {
                    BateauWindow::refreshAllTables();
                    QuaisWindow::refreshAll();
                    QTimer::singleShot(100, this, [this, nomBateau, numQuai](){
                        QMessageBox::information(this, "Accès Autorisé", nomBateau + " -> Quai " + QString::number(numQuai));
                    });
                }
            } else {
                A.write_to_arduino("F\n");
                QMessageBox::warning(this, "Port Complet", "Plus de place disponible.");
            }
        }
    } else {
        // AUCUN BATEAU TROUVÉ
        A.write_to_arduino("E\n");
        QTimer::singleShot(100, this, [this](){
            QMessageBox::critical(this, "Accès Refusé", "Code secret incorrect.");
        });
    }
}


void MainWindow::checkFridgeTemperature(int sensorId, double currentTemp)
{
    // Mapping: S1 -> FRG-001, S2 -> FRG-002
    QString fridgeRef = (sensorId == 1) ? "FRG-001" : "FRG-002";
    
    QSqlQuery query;
    query.prepare("SELECT TEMPERATURE FROM FRIGOS WHERE TRIM(REFERENCE) = :ref");
    query.bindValue(":ref", fridgeRef);
    
    double threshold = 0.0;
    bool thresholdFound = false;

    if (query.exec()) {
        if (query.next()) {
            threshold = query.value(0).toDouble();
            thresholdFound = true;
            qDebug() << "ALERTE DEBUG: Fridge" << fridgeRef << "| Temp:" << currentTemp << "| Seuil DB:" << threshold;
        } else {
            qDebug() << "ALERTE ERROR: Fridge" << fridgeRef << "not found in database! Using fallback threshold 10.0";
            threshold = 10.0; 
            thresholdFound = true; 
        }
    } else {
        qDebug() << "ALERTE SQL ERROR:" << query.lastError().text();
        threshold = 10.0; // Fallback even on SQL error for safety
        thresholdFound = true;
    }

    // Alert if temperature is TOO HOT
    if (thresholdFound && currentTemp > threshold) {
        currentlyInDanger.insert(fridgeRef);
        updateFrigoNotifications();
            
        // Send danger signal to Arduino OLED ONLY ONCE
        if (!arduinoNotifiedDanger.contains(fridgeRef)) {
            if (fridgeRef == "FRG-001") A.write_to_arduino("D1\n");
            else if (fridgeRef == "FRG-002") A.write_to_arduino("D2\n");
            arduinoNotifiedDanger.insert(fridgeRef);
            qDebug() << "Arduino notified: Danger Started for" << fridgeRef;
        }

        // Handle the unified popup alert
        if (!unifiedAlert) {
            if (QApplication::activeModalWidget()) {
                qDebug() << "Modal active. Skipping pop-up alert.";
            } else {
                QDateTime now = QDateTime::currentDateTime();
                if (lastDismissed.contains(fridgeRef) && lastDismissed[fridgeRef].addSecs(180) > now) {
                    qDebug() << "Cooldown active for" << fridgeRef;
                } else {
                    unifiedAlert = new TemperatureAlert(nullptr);
                    connect(unifiedAlert, &TemperatureAlert::requestNavigation, this, &MainWindow::onNavigateToFrigos, Qt::QueuedConnection);
                    connect(unifiedAlert, &TemperatureAlert::fridgesDismissed, this, [this](const QStringList& refs) {
                        QDateTime now = QDateTime::currentDateTime();
                        for (const QString& ref : refs) {
                            lastDismissed[ref] = now;
                        }
                    });
                    unifiedAlert->show();
                }
            }
        }
        
        if (unifiedAlert) {
            QDateTime now = QDateTime::currentDateTime();
            if (!(lastDismissed.contains(fridgeRef) && lastDismissed[fridgeRef].addSecs(180) > now)) {
                unifiedAlert->addOrUpdateFridge(fridgeRef, threshold, currentTemp);
            }
        }
    } else {
        // Temperature is back to normal
        if (currentlyInDanger.contains(fridgeRef)) {
            currentlyInDanger.remove(fridgeRef);
            updateFrigoNotifications();
            
            // Clear cooldown when resolved
            lastDismissed.remove(fridgeRef);
            
            if (unifiedAlert) {
                unifiedAlert->removeFridge(fridgeRef);
            }

            // Update Arduino state ONLY ONCE when returning to safe
            if (arduinoNotifiedDanger.contains(fridgeRef)) {
                if (fridgeRef == "FRG-001") A.write_to_arduino("OK1\n");
                else if (fridgeRef == "FRG-002") A.write_to_arduino("OK2\n");
                arduinoNotifiedDanger.remove(fridgeRef);
                qDebug() << "Arduino notified: Safe Again for" << fridgeRef;
            }

            if (currentlyInDanger.isEmpty()) {
                A.write_to_arduino("OK\n");
            }
        }
    }
}

void MainWindow::processRFIDPresence(const QString& uid)
{
    // Normalize UID: remove colons and spaces to ensure match
    QString cleanUid = uid.simplified().replace(":", "").replace(" ", "").toUpper();
    qDebug() << "Searching for normalized UID:" << cleanUid;

    QSqlQuery query;
    // Search using a normalized version of the stored UID as well
    QString sql = QString("SELECT ID_EMPLOYE, PRENOM, NOM FROM %1 WHERE UPPER(REPLACE(REPLACE(RFID_UID, ':', ''), ' ', '')) = :uid").arg(activeEmployeeTable);
    query.prepare(sql);
    query.bindValue(":uid", cleanUid);
    
    if (query.exec()) {
        if (query.next()) {
            int empId = query.value(0).toInt();
            QString name = query.value(1).toString() + " " + query.value(2).toString();
            
            QSqlQuery sessionQuery;
            sessionQuery.prepare("SELECT ID FROM PRESENCE WHERE ID_EMPLOYE = :id AND HEURE_DEPART IS NULL");
            sessionQuery.bindValue(":id", empId);
            
            if (sessionQuery.exec() && sessionQuery.next()) {
                int presenceId = sessionQuery.value(0).toInt();
                QSqlQuery updateQuery;
                updateQuery.prepare("UPDATE PRESENCE SET HEURE_DEPART = CURRENT_TIMESTAMP WHERE ID = :id");
                updateQuery.bindValue(":id", presenceId);
                if (updateQuery.exec()) {
                    A.write_to_arduino("0"); // Send 0 to Arduino (Goodbye)
                    QMessageBox::information(this, "Présence", "Au revoir " + name + " ! (Départ enregistré)");
                }
            } else {
                // Generate simple ID if needed (for tables without identity)
                int nextId = 1;
                QSqlQuery idQuery("SELECT MAX(ID) FROM PRESENCE");
                if (idQuery.next()) nextId = idQuery.value(0).toInt() + 1;

                QSqlQuery insertQuery;
                insertQuery.prepare("INSERT INTO PRESENCE (ID, ID_EMPLOYE, DATE_PRESENCE, HEURE_ARRIVEE) "
                                   "VALUES (:id_p, :id, CURRENT_DATE, CURRENT_TIMESTAMP)");
                insertQuery.bindValue(":id_p", nextId);
                insertQuery.bindValue(":id", empId);
                if (insertQuery.exec()) {
                    A.write_to_arduino("1"); // Send 1 to Arduino (Welcome)
                    QMessageBox::information(this, "Présence", "Bienvenue " + name + " ! (Arrivée enregistrée)");
                } else {
                    qDebug() << "Insert error:" << insertQuery.lastError().text();
                }
            }
        } else {
            qDebug() << "UID not found in database:" << cleanUid;
            A.write_to_arduino("X");
        }
    } else {
        qDebug() << "Query failed for" << activeEmployeeTable << ":" << query.lastError().text();
    }
}
